config/routes.rb
NusHelp::Application.routes.draw do

  get "nus_modules/module_all"
  get "activities/index"
  resources :users do
    member do
      get :followings, :followers , :mods, :liked_microposts, :posts, :show_gift_sent, :show_gift_received
      patch :json_upload
    end
  end
  
  resources :nus_modules do
    member do
      get :mod_followers
    end
  end

  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments
    member do
      get :likers , :helpers
    end
  end
  resources :activities
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likeships
  resources :module_followings, only: [:new, :create, :destroy, :insertModules]
  resources :help_recs

  root to: 'static_pages#home'
  match '/module_list', to: 'nus_modules#autoCompJson', via: 'get'
 

  match '/createmod', to: 'nus_modules#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signupmod', to: 'module_followings#new',  via: 'get'
  match '/insertModules', to: 'module_followings#insertModules',  via: 'get'
  match '/update_helpRec', to: 'help_recs#update', via: 'post'
  match '/module_followings', to: 'module_followings#create', via: 'POST'
  match '/module_followings_delete', to: 'module_followings#destroy', via: 'POST'
  match '/nus_modules/module_all', to: 'nus_modules#module_all', via: 'get'
  match '/nus_modules/(:id)/module_followings', to: 'module_followings#create', via: 'POST'
  match '/nus_modules/(:id)/module_followings_delete', to: 'module_followings#destroy', via: 'POST'
  
  match '/post_click', to: 'microposts#addClickCount', via: 'POST'
  match '/nus_modules/post_click', to: 'microposts#addClickCount', via: 'POST'
  match '/users/(:id)/post_click',to: 'microposts#addClickCount', via: 'POST'
  
  match '/notification_click', to: 'activities#updateStatus', via: 'POST'




  match '/feedback_helpRec', to: 'help_recs#feedback', via: 'POST'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  get '/search',  to: 'search#show'
  get '/search/:term',  to: 'search#show_term'

  match '/feedback', to: 'feedback#create', via: 'POST'
end

app/models/module_following.rb
class ModuleFollowing < ActiveRecord::Base
  include PublicActivity::Model
  tracked :skip_defaults => true
  attr_accessible :mod_id, :mod_follower_id

  belongs_to :mod_follower, class_name: "User"
  belongs_to :mod, class_name: "NusModule"

  validates :mod_follower_id, presence: true
  validates :mod_id, presence: true
end

app/controllers/module_followings_controller.rb
class ModuleFollowingsController < ApplicationController
  before_action :signed_in_user

  def new
    @user = current_user
  end

  def create
    currentModule = nil
    if(params[:mode] == "module")
      params[:mode] == ""
      params[:module_following][:mod_follower_id] = current_user.id
      mod_code = params[:module_following][:mod_id]
      currentModule = NusModule.find_by(:code => mod_code)
      params[:module_following][:mod_id] = currentModule.id
    end

    if ModuleFollowing.find_by(params[:module_following]).nil?
      @module_following = ModuleFollowing.new(params[:module_following])
    else
      @module_following = nil
    end  

    respond_to do |format|
      if @module_following!=nil && @module_following.save
        NusModule.where(:id=>params[:module_following][:mod_id]).update_all("follower_count = follower_count + 1")
        format.html { 
          @module_following.create_activity :create, owner: current_user
          redirect_to root_url 
        }
        format.json{
          render json: currentModule ? currentModule : @module_following,
          status: :created,
          location: @module_following
        }
      end
    end
  end

  def destroy
    if(params[:mode] == "module")
      params[:mode] == ""
      params[:module_following][:mod_follower_id] = current_user.id
      mod_code = params[:module_following][:mod_id]
      params[:module_following][:mod_id] = NusModule.find_by(:code => mod_code).id
    end
    @module_following = ModuleFollowing.find_by(params[:module_following])
    @nus_module = NusModule.find_by(params[:module_following][:mod_id])
    @module_following.destroy
    respond_to do |format|
      NusModule.where(:id=>params[:module_following][:mod_id]).update_all("follower_count = follower_count - 1")
      format.html { redirect_to @nus_module }
      format.json{
        render json: @module_following,
        status: :deleted,
        location: @module_following
      }
    end
  end

  def insertModules
    @module = get_user_module(params['token'])
    @module_token = get_token_modules(params['token'],params['account'])
    @mod = []
    for m in @module['Results']
      @mod.push({"code"=>m['CourseCode'], "name"=>m['CourseName']})
    end

    for m in @module_token['Results']
      @mod.push({"code"=>m['ModuleCode'], "name"=>m['ModuleTitle']})
    end
    @uid = params['uid']

    if @mod
      for m in @mod
        mod = NusModule.find_by(code: m['code'])
        unless mod.nil?
          params[:modFollow] = {:mod_id=>mod.id, :mod_follower_id=>params[:uid]}
          if ModuleFollowing.find_by(params[:modFollow]).nil?
            ModuleFollowing.create!(params[:modFollow])
          end  
        end
      end
    end

    user = User.find_by(id: params[:uid])
    if(user)
      render :new
    else
      redirect_to root_url
    end
  end

  def get_user_module(token)
    url = "https://ivle.nus.edu.sg/api/Lapi.svc/Modules?APIKey=x1oWBE5VN7HEynShRRjLv&AuthToken=#{token}&Duration=10&IncludeAllInfo=false";
    res = http_request(url)
    return ActiveSupport::JSON.decode(res.body)
  end

  def get_token_modules(token,studentID)
    url = "https://ivle.nus.edu.sg/api/Lapi.svc/Modules_Taken?APIKey=x1oWBE5VN7HEynShRRjLv&AuthToken=#{token}&StudentID=#{studentID}";
    res = http_request(url)
    return ActiveSupport::JSON.decode(res.body)
  end
end

app/helpers/module_followings_helper.rb
module ModuleFollowingsHelper
	
end

app/views/module_followings/_can_help_modules.html.erb
<div class="row-fluid" id="profile_fluid">
<div class="span8">
  <span class="help-block" id="module_help">  Modules I can also help</span>
</div>
<div class="span4">
  <input type="text" class="input-medium search-query">
  <button type="submit" class="btn">
    Search
  </button>
</div>
<span class="label">EG2401</span>
<span class="label">EG3002</span>
</div>

app/views/module_followings/create.js.erb
$("#mod_follow_form").html("<%= escape_javascript(render('nus_modules/unfollowMod')) %>")
$("#mod_followers").html('<%= @nus_module.mod_followers.count %>')

app/views/module_followings/destroy.js.erb
$("#mod_follow_form").html("<%= escape_javascript(render('nus_modules/followMod')) %>")
$("#mod_followers").html('<%= @nus_module.mod_followers.count %>')

app/views/module_followings/new.html.erb
<% content_for :content do %>
  <% if current_user %>
    <div class="well">
      <% if current_user.mods.any? %>
        <h4>Modules I'm Following:</h4>
        <div class="module-tags">
          <% current_user.mods.each do |m| %>
            <span class="module-tag needToolTip">
              <%= link_to m.code, m ,:title=>m.name%><a class="close needToolTip unfollow" title="Unfollow">x</a></span>
          <% end %>
        </div>
      <% else %>
        <h4>You're not following any module yet.</h4>
        <div class="module-tags">
        </div>
      <% end %>
      <div class="search-query">
        <%= form_tag nus_modules_path, :method => 'get' do %>
          <div id="resize_box">
            <%= text_field_tag :searchm ,params[:searchm], data: {autocomplete_source: module_list_url}, placeholder: "Filling any modules you want to follow" %>
          </div>
          <div id="hide_submit">
            <%= submit_tag "Search", :name => nil  %>
          </div>
        <% end %>
      </div>
    </div>
    <%= link_to "Finish", @user ,:class => "btn"%>
  <% end %>
<% end %>