config/routes.rb
NusHelp::Application.routes.draw do

  get "nus_modules/module_all"
  get "activities/index"
  resources :users do
    member do
      get :followings, :followers , :mods, :liked_microposts, :posts, :show_gift_sent, :show_gift_received
      patch :json_upload
    end
  end
  
  resources :nus_modules do
    member do
      get :mod_followers
    end
  end

  resources :microposts, only: [:create, :destroy, :show] do
    resources :comments
    member do
      get :likers , :helpers
    end
  end
  resources :activities
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likeships
  resources :module_followings, only: [:new, :create, :destroy, :insertModules]
  resources :help_recs

  root to: 'static_pages#home'
  match '/module_list', to: 'nus_modules#autoCompJson', via: 'get'
 

  match '/createmod', to: 'nus_modules#new', via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/signupmod', to: 'module_followings#new',  via: 'get'
  match '/insertModules', to: 'module_followings#insertModules',  via: 'get'
  match '/update_helpRec', to: 'help_recs#update', via: 'post'
  match '/module_followings', to: 'module_followings#create', via: 'POST'
  match '/module_followings_delete', to: 'module_followings#destroy', via: 'POST'
  match '/nus_modules/module_all', to: 'nus_modules#module_all', via: 'get'
  match '/nus_modules/(:id)/module_followings', to: 'module_followings#create', via: 'POST'
  match '/nus_modules/(:id)/module_followings_delete', to: 'module_followings#destroy', via: 'POST'
  
  match '/post_click', to: 'microposts#addClickCount', via: 'POST'
  match '/nus_modules/post_click', to: 'microposts#addClickCount', via: 'POST'
  match '/users/(:id)/post_click',to: 'microposts#addClickCount', via: 'POST'
  
  match '/notification_click', to: 'activities#updateStatus', via: 'POST'




  match '/feedback_helpRec', to: 'help_recs#feedback', via: 'POST'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/privacy', to: 'static_pages#privacy'

  get '/search',  to: 'search#show'
  get '/search/:term',  to: 'search#show_term'

  match '/feedback', to: 'feedback#create', via: 'POST'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  include PublicActivity::Model
  tracked :skip_defaults => true

  #tracked owner: ->(controller, model) { controller && controller.current_user }
  attr_accessible :name, :email, :account, :remember_token, :microposts_attributes, :gender

  has_one :user_img
  has_many :comments
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name:  "Relationship", dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_likeships, foreign_key: "liker_id", class_name: "Likeship", dependent: :destroy
  has_many :liked_microposts, through: :reverse_likeships
  has_many :reverse_module_followings, foreign_key: "mod_follower_id", class_name: "ModuleFollowing", dependent: :destroy
  has_many :mods, through: :reverse_module_followings

  accepts_nested_attributes_for :microposts, allow_destroy: true
  before_save { self.email = email.downcase }
  # before_save :create_remember_token


  before_save { |user| user.email = email.downcase }
  validates :account, presence: true, uniqueness: { case_sensitive: false }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  validates :remember_token, presence: true
  validates :gender, presence:true

  def feed
    Micropost.from_users_followed_by(self)
  end

  def mod_feed
    Micropost.from_modules_following(self)
  end

  def findModule(code)
    NusModule.findModule(code)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def gender_text
    self.gender == 0 ? "male" : "female"
  end

  def cropped_img_url
    if self.user_img.nil? or self.user_img.cropped_url.nil?
      UserImg::DefaultCroppedUrl
    else
      self.user_img.cropped_url
    end
  end

  # private

  #   def create_remember_token
  #     self.remember_token = SecureRandom.urlsafe_base64
  #   end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>*
          <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feed_items.any? %>
  <ul class="nav nav-list" id="homehelpFeeds">
    <%= render partial: 'shared/feed_item', collection: feed_items %>
  </ul>
  <%= will_paginate  feed_items%>
<% else %>
  <em>There's no feed yet.</em>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="help">
    <div class="bookmark">
    <% case feed_item.status %>
    <% when 0 %>
      <%= image_tag "bookmark-green.png" , :size=> "15x15"%>
    <% when 1 %>
      <%= image_tag "bookmark-blue.png" , :size=> "15x15"%>
    <% when 2 %>
      <%= image_tag "bookmark-red.png" , :size=> "15x15"%>
    <% end %>
    </div>
    <div class="helpcontent">
      <% if feed_item.is_anonymous == true %>
        <%= render "users/anonymous_photo",{user:feed_item.user,need_div: true, size:50} %>
      <% else %>
        <%= render "users/user_photo",{user:feed_item.user,need_div: true, size:50} %>
      <% end %>
      <div class="help-feeds">
        <div class="record" id="comment-record">
          <div class='countNumber'>
            <%= link_to feed_item.comments.count,feed_item,{:style=>'color:white'} %>
          </div>
          <strong id="comment-strong">Comments</strong>
        </div>
        <div class="record">
          <div class='countNumber'>
            <%= link_to feed_item.help_recs.count,feed_item,{:style=>'color:#870a0a'} %>
          </div>
          <strong id="helper-strong">Helpers</strong>
        </div>
        <div class="record">
          <div class='countNumber'>
            <%= link_to feed_item.click_count,feed_item,{:style=>'color:#dadbd8'} %>
          </div>
          <strong id="click-strong">Clicks</strong>
        </div>

          <span class='itemTitle click_count' data-id=<%=feed_item.id%> >
            <%= link_to feed_item.title, feed_item %>
          </span>
          <div class='sep8'></div>
          <span class='smallNode gray'>
            <% @module = NusModule.find_by(id: feed_item.module_id) %>
            <%= link_to @module.code,@module, {:style => 'background-color:#CCC'} %>
            <%= " | " %>
            <% if feed_item.is_anonymous == true %>
              <%= link_to 'Anonymous','#',{:style => 'color:gray'} %>
            <% else %>
              <%= link_to feed_item.user.name, feed_item.user, {:style => 'color:gray'} %>
            <% end %>
            <%= " | " %>
            <% case feed_item.status %>
            <% when 0 %>
            <% @status="Ongoing" %>
            <% when 1 %>
            <% @status="Helper Choosed" %>
            <% when 2 %>
            <% @status="Gift Given"%>
          <% else %>
            <% @status="Status Error"%>
          <% end %>
          <%= link_to @status, feed_item, {:style => 'color: gray'} %>
          <%= " | " %>
          <span class='mytimestamp'>
            <%= time_ago_in_words(feed_item.created_at) +" ago"%>
          </span>
          <div class="gift">
            <i class='icon-gift'></i>
            <%= feed_item.gift %>
                      |
          <% if feed_item.is_online %>
          Online Help
          <% else %>
          Offline Help
          <% end %>
          </div>
          <div>
            <% if current_user.admin? %>
                <%= link_to "delete", feed_item, method: :delete,
                                    data: { confirm: "You sure?" } %>
            <% end %>
          </div>
        </span>
    </div>
  </div>
</div>
</li>

app/views/shared/_micropost_form.html.erb
<div class="post-task">
  <h4>
    New Help:
  </h4>
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field input-xlarge">
    <h6>Title:</h6>
    <%= f.text_field :title, placeholder: "Less than 25 words" %>
    <h6>Task Description:</h6>
    <%= f.text_area :content, placeholder: "Describe your task in details to make people help you in a better way..." %>
    <%= f.hidden_field :is_anonymous, :value => false %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div>
      <div class="post-task-cell">
      <h6>Deadline:</h6>
      <%= f.text_field :deadline %>
      </div>
      <div class="post-task-cell">
      <h6>Module Code:</h6>
      <%= f.text_field :module_code, data: {autocomplete_source: module_list_url} %>
      <%= f.hidden_field :module_id %>
      </div>
    </div>
    <div>
      <h6>Thank-you Gift:</h6>
      <%= f.text_field :gift, placeholder: "Gift to the helper" %>
    </div>
    <div class="field">
        <%= f.radio_button :is_online, true , :checked => true %> Online
        <%= f.radio_button :is_online, false %> Offline
    </div>
    <div>
      <h6>
      <%= f.check_box :is_anonymous %> Anonymous
      </h6> 
    </div>
  </div>
  <%= f.submit "Post Help", class: "btn btn-default btn-primary", id: "post_submit" %>
<% end %>
</div>

app/views/shared/_notifications.html.erb
<li id="fat-menu" class="dropdown">
<% followed_user_ids = "SELECT followed_id FROM relationships
                          WHERE follower_id = :user_id" %>
<%  @activities = PublicActivity::Activity.order("created_at desc").where("recipient_id = (:user_id)", user_id: current_user.id) %>
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  <div class="notificationNumber">
    <%= unreadNum(@activities) %>
  </div>
</a>
<ul class="dropdown-menu mydropdown-menu"><%= link_to "" ,activities_path %>
  <%= render :partial=>'activities/dropdownList', :collections => @activities%>
</ul>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<span>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= user_render.followed_users.count %>
    </strong>
    following users
  </a>
</span>
<span>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.mods.count %>
    </strong>
  </a>
</span>
<span>
  <a href="<%= followers_user_path(user_render) %>">
    <strong id="followers" class="stat">
      <%= user_render.followers.count %>
    </strong>
    following modules
  </a>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>

app/views/shared/_user_info.html.erb
<% user_render = @user || current_user %>
<div class="user-info-pad">
  <div>
    <%= render 'shared/user_photo' %>
  </div>
</br>
  <div>
    <%= render 'shared/stats' %>
  </div>
<h3>
  <%= link_to user_render.name, user_render %>
</h3>

app/views/shared/_user_photo.html.erb
<% size = "30x30" if (size and size == :small) else "180*180" %>
<% user_render = @user.nil? ? current_user : @user %>
<a href="<%= user_path(user_render) %>">
  <% if user_render.photo.to_s == "/uploads/user/photo/#{user_render.id}/0".to_s %>
    <% if user_render.gender == 0 %>
      <%= image_tag "man.jpeg" , :size => size, :crop => :fill%>
    <% else %>
      <%= image_tag "women.jpeg" , :size => size, :crop => :fill%>
    <% end %> 
  <% else %>
    <%= image_tag user_render.photo_small, :size => size, :crop => :fill%>
  <% end %>
</a>